[TeamItems] CAES-1201: Fix items decryption
caesar-team/caesar-web-client pull request #442
Opened 2020-08-21 08:24 UTC by sa715

Signed-off-by: Sergey Alekseyev <sa@4xxi.com>

2020-08-21 08:52 UTC, cu4xxi commented on packages/common/sagas/workflow.js
> +    console.log('Init team');
консоль

2020-08-26 11:52 UTC, beshkenadze commented on packages/common/sagas/entities/item.js
> +        console.log('System data');
Please, remove the console calls.

2020-08-26 11:53 UTC, beshkenadze requested changes

2020-08-26 11:53 UTC, beshkenadze commented on packages/common/selectors/entities/item.js
> +//        console.log(systemItems);
Please, remove the commented lines

2020-08-26 12:02 UTC, sa715 commented on packages/common/selectors/entities/item.js
> +//        console.log(systemItems);
Done

2020-08-26 12:03 UTC, sa715 commented on packages/common/sagas/entities/item.js
> +        console.log('System data');
Done

2020-08-26 12:06 UTC, beshkenadze approved these changes

2020-08-26 12:11 UTC, merged