[Teams] CAES-1276: Add ability to leave team
caesar-team/caesar-web-client pull request #478
Opened 2020-09-17 08:34 UTC by sa715

Signed-off-by: Sergey Alekseyev <sa@4xxi.com>

2020-09-17 09:54 UTC, cu4xxi requested changes

2020-09-17 09:54 UTC, cu4xxi commented on packages/assets/icons/svg/icon-leave.svg
> +        <g transform="translate(-660.000000, -314.000000)">
посмотри эту иконку на полотне с иконками, чтобы не было лишних трансформов.
если ее там нет, попроси Катю, чтобы она ее "почистила" и добавила на полотно

2020-09-17 09:54 UTC, cu4xxi commented on packages/common/constants.js
> +  SETTINGS_TEAMS: '/settings/team',
вместо этого я везде писала в коде
`ROUTES.SETTINGS + ROUTES.TEAM`

2020-09-17 09:54 UTC, cu4xxi commented on packages/components/TeamCard/TeamCard.js
> +            <MenuButton color="white" onClick={onClickLeaveTeam}>
если ты будешь обычным юзером (без возможности редактирования и удаления команды), у тебя эта выпадашка не будет доступна. 
там выше есть компонент Can в котором прописаны правила круд. 
если эту кнопку надо отображать всегда, тогда верхний Can можешь просто убрать.

2020-09-17 09:54 UTC, cu4xxi commented on packages/containers/TeamList/TeamList.js
> +          description="You will lose access to the team items. Are you sure?"
один и тот же попап, разнятся немного в том, как и какие методы передаются.
давай сделаем компонент в common/components?

2020-09-17 11:35 UTC, sa715 commented on packages/assets/icons/svg/icon-leave.svg
> +        <g transform="translate(-660.000000, -314.000000)">
Done

2020-09-17 11:35 UTC, sa715 commented on packages/common/constants.js
> +  SETTINGS_TEAMS: '/settings/team',
Done

2020-09-17 11:35 UTC, sa715 commented on packages/components/TeamCard/TeamCard.js
> +            <MenuButton color="white" onClick={onClickLeaveTeam}>
Done

2020-09-17 11:35 UTC, sa715 commented on packages/containers/TeamList/TeamList.js
> +          description="You will lose access to the team items. Are you sure?"
Done

2020-09-17 13:14 UTC, cu4xxi approved these changes

2020-09-18 07:52 UTC, rtatarinov4xxi approved these changes

2020-09-18 08:05 UTC, merged